### ISSUE TITLE
Some results have no scan status or results

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#200]
For ~100 or so URLs, there's no scan date, scan status, or scan results.  

* Investigate why it's happening. 
* Plan and implement a change to keep it from happening.  

Even if the scans fail and thus there are no results, there should still be at least scan dates and statuses.

**Comment by danielnaab** [comment]
This may be a representative error log for these sites:

```
{
  "level": 50,
  "time": 1647995513282,
  "pid": 105,
  "hostname": "5b293fef-e0ff-4ceb-4e9b-634f",
  "context": "ScanEngineConsumer",
  "err": {
    "type": "Error",
    "message": "invalid input syntax for type integer: \"NaN\"",
    "stack": "QueryFailedError: invalid input syntax for type integer: \"NaN\"\n    at QueryFailedError.TypeORMError [as constructor] (/home/vcap/deps/1/node_modules/typeorm/error/TypeORMError.js:9:28)\n    at new QueryFailedError (/home/vcap/deps/1/node_modules/typeorm/error/QueryFailedError.js:13:28)\n    at PostgresQueryRunner.<anonymous> (/home/vcap/deps/1/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:250:31)\n    at step (/home/vcap/deps/1/node_modules/tslib/tslib.js:143:27)\n    at Object.throw (/home/vcap/deps/1/node_modules/tslib/tslib.js:124:57)\n    at rejected (/home/vcap/deps/1/node_modules/tslib/tslib.js:115:69)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  },
  "msg": "invalid input syntax for type integer: \"NaN\""
}
```

**Comment by lgarceau768** [comment]
Link to the PR https://github.com/GSA/site-scanning-engine/pull/173

**Comment by lgarceau768** [comment]
All the requested changes have been made for this PR, should be able to merge after verifying test coverage.

**Comment by gbinal** [comment]
confirmed that this is now working.  wahoo!

**Comment by gbinal** [comment]
alas, it looks like maybe this is still happening.

**Comment by gbinal** [comment]
this looks good, closing
